In [11]:
import numpy as np
import pandas as pd
import seaborn as sn

In [12]:
df=pd.read_csv("D:/extra/udemy_machine/classification/Classification+preprocessed+data+Python.csv",header=0)

In [13]:
df.describe()

price  resid_area    air_qual    room_num         age    teachers  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    22.528854   41.136779    0.554695    6.284634   68.574901   21.544466   
std      9.182176    6.860353    0.115878    0.702617   28.148861    2.164946   
min      5.000000   30.460000    0.385000    3.561000    2.900000   18.000000   
25%     17.025000   35.190000    0.449000    5.885500   45.025000   19.800000   
50%     21.200000   39.690000    0.538000    6.208500   77.500000   20.950000   
75%     25.000000   48.100000    0.624000    6.623500   94.075000   22.600000   
max     50.000000   57.740000    0.871000    8.780000  100.000000   27.400000   

        poor_prop  n_hos_beds  n_hot_rooms    rainfall       parks  \
count  506.000000  506.000000   506.000000  506.000000  506.000000   
mean    12.653063    7.899767    12.864050   39.187747    0.054454   
std      7.141062    1.464939     2.688778   12.497221    0.010632   
min      1.730000    5.268000    10.057600    6.000000    0.033292   
25%      6.950000    6.659000    11.189800   28.000000    0.046464   
50%     11.360000    7.963000    12.720000   39.000000    0.053507   
75%     16.955000    9.076000    14.170800   50.000000    0.061397   
max     37.970000   10.876000    46.198560   60.000000    0.086711   

             Sold    avg_dist  airport_YES  waterbody_Lake  \
count  506.000000  506.000000   506.000000      506.000000   
mean     0.454545    3.795104     0.551383        0.191700   
std      0.498422    2.105859     0.497845        0.394028   
min      0.000000    1.127500     0.000000        0.000000   
25%      0.000000    2.100625     0.000000        0.000000   
50%      0.000000    3.207500     1.000000        0.000000   
75%      1.000000    5.187500     1.000000        0.000000   
max      1.000000   12.127500     1.000000        1.000000   

       waterbody_Lake and River  waterbody_River  
count                506.000000       506.000000  
mean                   0.140316         0.361660  
std                    0.347659         0.480957  
min                    0.000000         0.000000  
25%                    0.000000         0.000000  
50%                    0.000000         0.000000  
75%                    0.000000         1.000000  
max                    1.000000         1.000000

In [14]:
x=df.loc[:,df.columns!='Sold']#independent variable two dimension so we us[[]]


In [15]:
y=df['Sold']

In [16]:
x.head()

price  resid_area  air_qual  room_num   age  teachers  poor_prop  \
0   24.0       32.31     0.538     6.575  65.2      24.7       4.98   
1   21.6       37.07     0.469     6.421  78.9      22.2       9.14   
2   34.7       37.07     0.469     7.185  61.1      22.2       4.03   
3   33.4       32.18     0.458     6.998  45.8      21.3       2.94   
4   36.2       32.18     0.458     7.147  54.2      21.3       5.33   

   n_hos_beds  n_hot_rooms  rainfall     parks  avg_dist  airport_YES  \
0       5.480     11.19200        23  0.049347    4.0875            1   
1       7.332     12.17280        42  0.046146    4.9675            0   
2       7.394     46.19856        38  0.045764    4.9675            0   
3       9.268     11.26720        45  0.047151    6.0650            1   
4       8.824     11.28960        55  0.039474    6.0625            0   

   waterbody_Lake  waterbody_Lake and River  waterbody_River  
0               0                         0                1  
1               1                         0                0  
2               0                         0                0  
3               1                         0                0  
4               1                         0                0

In [17]:
y.head()

0    0
1    1
2    0
3    0
4    0
Name: Sold, dtype: int64

In [18]:
from sklearn.linear_model import LogisticRegression

In [19]:
clf_lrs=LogisticRegression()

In [20]:
clf_lrs.fit(x,y)

f:\Python\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [21]:
clf_lrs.coef_ #(Beta0)

array([[-0.24635709, -0.01729752, -0.11019455,  0.86260903, -0.00599865,
         0.22819614, -0.21021829,  0.18006652, -0.09086611, -0.00704704,
        -0.00499205, -0.32611303, -0.105213  , -0.09487407, -0.01512373,
         0.20180456]])

In [22]:
clf_lrs.intercept_

array([0.01671289])

In [23]:
import statsmodels.api as sn

In [24]:
x_cons=sn.add_constant(x)  #without constan Bet0=0 so add constant

In [25]:
x_cons.head()

const  price  resid_area  air_qual  room_num   age  teachers  poor_prop  \
0    1.0   24.0       32.31     0.538     6.575  65.2      24.7       4.98   
1    1.0   21.6       37.07     0.469     6.421  78.9      22.2       9.14   
2    1.0   34.7       37.07     0.469     7.185  61.1      22.2       4.03   
3    1.0   33.4       32.18     0.458     6.998  45.8      21.3       2.94   
4    1.0   36.2       32.18     0.458     7.147  54.2      21.3       5.33   

   n_hos_beds  n_hot_rooms  rainfall     parks  avg_dist  airport_YES  \
0       5.480     11.19200        23  0.049347    4.0875            1   
1       7.332     12.17280        42  0.046146    4.9675            0   
2       7.394     46.19856        38  0.045764    4.9675            0   
3       9.268     11.26720        45  0.047151    6.0650            1   
4       8.824     11.28960        55  0.039474    6.0625            0   

   waterbody_Lake  waterbody_Lake and River  waterbody_River  
0               0                         0                1  
1               1                         0                0  
2               0                         0                0  
3               1                         0                0  
4               1                         0                0

In [26]:
import statsmodels.discrete.discrete_model as sn

In [27]:
logit=sn.Logit(y,x_cons).fit() #add constant term in to variable

Optimization terminated successfully.
         Current function value: 0.556433
         Iterations 6


In [28]:
logit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                   Sold   No. Observations:                  506
Model:                          Logit   Df Residuals:                      489
Method:                           MLE   Df Model:                           16
Date:                Sat, 19 Nov 2022   Pseudo R-squ.:                  0.1924
Time:                        08:49:12   Log-Likelihood:                -281.56
converged:                       True   LL-Null:                       -348.64
Covariance Type:            nonrobust   LLR p-value:                 9.930e-21
============================================================================================
                               coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------
const                       -2.1383      2.649     -0.807      0.420      -7.331       3.054
price                       -0.2741      0.033     -8.313      0.000      -0.339      -0.209
resid_area                   0.0192      0.027      0.720      0.471      -0.033       0.071
air_qual                    -7.4183      2.691     -2.757      0.006     -12.693      -2.144
room_num                     1.1067      0.277      4.001      0.000       0.565       1.649
age                         -0.0020      0.007     -0.302      0.762      -0.015       0.011
teachers                     0.3150      0.064      4.937      0.000       0.190       0.440
poor_prop                   -0.2077      0.034     -6.149      0.000      -0.274      -0.141
n_hos_beds                   0.1760      0.071      2.467      0.014       0.036       0.316
n_hot_rooms                 -0.0742      0.052     -1.439      0.150      -0.175       0.027
rainfall                    -0.0033      0.008     -0.394      0.693      -0.020       0.013
parks                       29.1089     24.177      1.204      0.229     -18.277      76.495
avg_dist                    -0.4017      0.098     -4.118      0.000      -0.593      -0.211
airport_YES                 -0.1524      0.211     -0.723      0.469      -0.565       0.261
waterbody_Lake              -0.1032      0.304     -0.340      0.734      -0.698       0.492
waterbody_Lake and River    -0.0626      0.328     -0.191      0.849      -0.705       0.580
waterbody_River              0.2394      0.256      0.937      0.349      -0.262       0.740
============================================================================================
"""

In [29]:
clf_lrs.predict_proba(x)

array([[0.12706719, 0.87293281],
       [0.39754999, 0.60245001],
       [0.98071831, 0.01928169],
       ...,
       [0.28594246, 0.71405754],
       [0.28061034, 0.71938966],
       [0.16347219, 0.83652781]])

In [31]:
y_pred=clf_lrs.predict(x)
y_pred

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,

In [32]:
y_pred_03=(clf_lrs.predict_proba(x)[:,1]>0.3)

In [33]:
y_pred_03

array([ True,  True, False,  True, False, False,  True, False, False,
        True,  True,  True, False,  True,  True,  True,  True, False,
        True,  True, False,  True, False, False,  True,  True,  True,
        True,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False, False,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True, False,  True,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
        True,  True,  True,  True,  True,  True, False, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False,  True,
       False, False,

In [34]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y,y_pred)

array([[196,  80],
       [ 81, 149]], dtype=int64)

In [35]:
from sklearn.metrics import precision_score,recall_score

In [36]:
precision_score(y,y_pred)

0.6506550218340611

In [37]:
recall_score(y,y_pred)

0.6478260869565218

In [38]:
from sklearn.metrics import roc_auc_score

In [39]:
roc_auc_score(y,y_pred)

0.6789855072463769

In [40]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [41]:
clf_lda=LinearDiscriminantAnalysis()
clf_lda.fit(x,y)

LinearDiscriminantAnalysis()

In [42]:
y_pred_lda=clf_lda.predict(x)

In [43]:
y_pred_lda

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,

In [44]:
confusion_matrix(y,y_pred_lda)

array([[192,  84],
       [ 79, 151]], dtype=int64)